services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/typechat/server/src
    
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/typechat/web/src
    depends_on:
      - server
